In [ ]:
from datetime import datetime
import pandas as pd
import requests
from pandas import json_normalize

* The SerpstatKeywordProcedure.getRelatedKeywords method 
* Shows all search queries that are semantically related to the searched keyword. 
* The data set is similar to the Keyword research / Related keywords report.

In [2]:
api_token = '185b0a40fdd3abccb33f353c8e3e2918'                                                         
api_url_pattern = 'https://api.serpstat.com/v{version}?token={token}'
api_url = api_url_pattern.format(version=4, token=api_token)

headers = {
    "Content-Type": "application/json",
    "X-Api-Key": f"{api_token}",
}

data = {
    "id": 1,
    "method": "SerpstatKeywordProcedure.getRelatedKeywords",
    "params": {
        "keyword": "guns near me",
        "se": "g_us",
        "sort": {"region_queries_count":"desc"},
        "page": 1,
        "size": 10
    }
}

api_resp = requests.post(api_url, json=data, headers=headers)
json_response = api_resp.json()
sliced_json = json_response['result']['data']
df = pd.json_normalize(sliced_json)
df

,keyword,region_queries_count,cost,concurrency,geo_names,types,right_spelling,weight,difficulty
0,academy sports outdoors near me,301000,0.060000,12,[],"[also_asks, local_pack, related_search, kn_gra...",None,1,43.0
1,sports academy and outdoors near me,301000,0.060000,12,[],"[kn_graph_local, also_asks, related_search, sn...",None,1,44.0
2,ball bearing guns,201000,0.170000,8,[],"[video, also_asks, related_search, pic, snip_b...",None,1,57.0
3,bb g,201000,0.170000,8,[],"[related_search, also_asks, pic, snip_breadcru...",None,1,38.0
4,bb gun,201000,0.170000,8,[],"[related_search, also_asks, snip_breadcrumbs]",None,1,44.0
5,bb gunning,201000,0.170000,8,[],"[also_asks, pic, related_search, snip_breadcru...",None,1,53.0
6,bee bee guns,201000,0.170000,8,[],"[also_asks, snip_breadcrumbs]",None,1,61.0
7,beebee gun,201000,0.170000,6,[],"[also_asks, pic, snip_breadcrumbs, snip_image_...",None,1,53.0
8,nearest academy sports to me,135000,0.070000,27,[],"[local_pack, also_asks, related_search, snip_b...",None,1,NaN
9,electric squirt gun,27100,0.259999,49,[],"[related_search, snip_breadcrumbs, snip_image_...",None,1,18.0